### ISSUE TITLE
Need further assistance

### ISSUE THREAD

**Issue by idata5102992** [liulizhi1996/HPOLabeler#1]
I am writing to inquire about the specific methods used in your work, particularly regarding the gene-HPO annotation file ALL_SOURCES_ALL_FREQUENCIES_genes_to_phenotype.txt. Could you please provide further details on the methodology and any additional insights you might have? Your expertise on this matter would be greatly appreciated.

**Comment by liulizhi1996** [comment]
HPO’s official website (https://hpo.jax.org/) was revised two years ago. If you need to download the gene-phenotype annotation file, you can click "Data -> Annotations" on the official website and then click "PHENOTYPE TO GENES" button to download the corresponding file.

It should be emphasized that due to the website revision, it is no longer possible to download the annotation files of previous versions. If you want to perform experiments in the temporal validation section, you can only contact the authors of HPO to obtain the old releases.
